table MEDIDAS
	lineageTag: 9c3d27fe-fc08-443e-a601-0d4371e12ad2

	measure sum_of_sales = SUM(FactRepuestosUsados[CostoTotal])
		lineageTag: 07d20019-5c35-4b3a-9eeb-5cfce9afa735

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure NUM_ORDERS = COUNTROWS(FactOrdenesTrabajo)
		formatString: 0
		lineageTag: b8777fb5-3df6-441f-a00a-5eebc223080c

	measure BENEFICIO_MANTENIMIENTO = CALCULATE(SUM(FactRepuestosUsados[CostoTotal]), DimServicio[Categoria] = "Mantenimiento")
		lineageTag: 5f683512-f1e4-42fb-a358-cfbe4e1e13a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BENEFICIO_REPARACION = CALCULATE(SUM(FactOrdenesTrabajo[CostoTotal]), DimServicio[Categoria] = "Reparación")
		lineageTag: c282b3eb-89b7-4bd3-b3be-2cdc67d55550

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BENEFICIO_ELECTRICO = CALCULATE(SUM(FactOrdenesTrabajo[CostoTotal]), DimServicio[Categoria] = "Eléctrico")
		lineageTag: e6e9e136-6307-49d8-8e30-d51ea8311d1c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ORDENES_COMPLETADAS = CALCULATE(COUNTROWS(FactOrdenesTrabajo), FactOrdenesTrabajo[Estado] = "Terminado")
		formatString: 0
		lineageTag: 0d1aa70a-935b-41bd-bbcd-0be8e381a9ea

	measure ORDENES_COMPLETAS_PORCENTAJE = [ORDENES_COMPLETADAS]/[NUM_ORDERS]
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 4d06440d-87ab-4093-9667-f4ab09dfce9f

	measure NUM_TECNICOS = COUNTROWS(DimTecnico)
		formatString: 0
		lineageTag: 32cf667d-403e-4e5d-8450-9505c52409dd

	measure EFICIENCIA_TECNICOS = ```
			
			DIVIDE(
			    CALCULATE( AVERAGE( FactOrdenesTrabajo[TiempoEstimado] ) ),
			    CALCULATE( AVERAGE( FactOrdenesTrabajo[TiempoReal] ) )
			)
			
			```
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 4d9721da-ef09-4422-8e8a-60f401e2a460

	measure RANK_TECNICOS = ```
			
			RANKX(
			    ALL( DimTecnico[NombreTecnico] ),
			    [EFICIENCIA_TECNICOS],
			    ,
			    DESC,
			    DENSE
			)
			
			```
		formatString: 0
		lineageTag: cbe73dce-7398-4cdc-89d4-747ffb338177

	measure ORDENES_ENPROCESO = CALCULATE(COUNTROWS(FactOrdenesTrabajo), FactOrdenesTrabajo[Estado] = "En Proceso")
		formatString: 0
		lineageTag: f714981a-a839-4c4c-8d25-343d39fc648e

	measure ORDENES_ENPROCESO_PORCENTAJE = [ORDENES_ENPROCESO]/[NUM_ORDERS]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: d99e701a-9421-457c-bb99-993b48f9e93b

	measure ORDENES_PENDIENTE = CALCULATE(COUNTROWS(FactOrdenesTrabajo), FactOrdenesTrabajo[Estado] = "Pendiente")
		formatString: 0
		lineageTag: c84954c9-8b0a-40da-ad11-f38025f3e931

	measure ORDENES_PENDIENTE_PORCENTAJE = [ORDENES_PENDIENTE]/[NUM_ORDERS]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: b66c45fb-12a2-474e-b308-221c3200591b

	measure BENEFICIO_ALINEACION = CALCULATE(SUM(FactOrdenesTrabajo[CostoTotal]), DimServicio[Categoria] = "Alineación")
		lineageTag: 058f6529-f383-4277-95f5-da716d416c04

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BENEFICIO_INSPECCION = CALCULATE(SUM(FactOrdenesTrabajo[CostoTotal]), DimServicio[Categoria] = "Inspección")
		lineageTag: ccd3d946-5d5b-4881-9a27-3f4ceef7eebc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BENEFICIO_REVISION = CALCULATE(SUM(FactOrdenesTrabajo[CostoTotal]), DimServicio[Categoria] = "Revisión")
		lineageTag: f321f0b2-9190-46e0-8138-fef25be360d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BENEFICIO_SUSPENSION = CALCULATE(SUM(FactOrdenesTrabajo[CostoTotal]), DimServicio[Categoria] = "Suspensión")
		lineageTag: 301cf6c7-d5e9-4d83-8425-5c28ee86d5b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition MEDIDAS = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

