table MEDIDAS
	lineageTag: 9c3d27fe-fc08-443e-a601-0d4371e12ad2

	measure sum_of_sales = SUM(FactRepuestosUsados[CostoTotal])
		lineageTag: 07d20019-5c35-4b3a-9eeb-5cfce9afa735

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure NUM_ORDERS = COUNTROWS(FactOrdenesTrabajo)
		formatString: 0
		lineageTag: b8777fb5-3df6-441f-a00a-5eebc223080c

	measure BENEFICIO_MANTENIMIENTO = CALCULATE(SUM(FactRepuestosUsados[CostoTotal]), DimServicio[Categoria] = "Mantenimiento")
		lineageTag: 5f683512-f1e4-42fb-a358-cfbe4e1e13a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BENEFICIO_REPARACION = CALCULATE(SUM(FactOrdenesTrabajo[CostoTotal]), DimServicio[Categoria] = "Reparación")
		lineageTag: c282b3eb-89b7-4bd3-b3be-2cdc67d55550

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BENEFICIO_ELECTRICO = CALCULATE(SUM(FactOrdenesTrabajo[CostoTotal]), DimServicio[Categoria] = "Eléctrico")
		lineageTag: e6e9e136-6307-49d8-8e30-d51ea8311d1c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ORDENES_COMPLETADAS = CALCULATE(COUNTROWS(FactOrdenesTrabajo), FactOrdenesTrabajo[Estado] = "Terminado")
		formatString: 0
		lineageTag: 0d1aa70a-935b-41bd-bbcd-0be8e381a9ea

	measure ORDENES_COMPLETAS_PORCENTAJE = [ORDENES_COMPLETADAS]/[NUM_ORDERS]
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 4d06440d-87ab-4093-9667-f4ab09dfce9f

	measure NUM_TECNICOS = COUNTROWS(DimTecnico)
		formatString: 0
		lineageTag: 32cf667d-403e-4e5d-8450-9505c52409dd

	measure EFICIENCIA_TECNICOS = ```
			
			DIVIDE(
			    CALCULATE( AVERAGE( FactOrdenesTrabajo[TiempoEstimado] ) ),
			    CALCULATE( AVERAGE( FactOrdenesTrabajo[TiempoReal] ) )
			)
			
			```
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 4d9721da-ef09-4422-8e8a-60f401e2a460

	measure RANK_TECNICOS = ```
			
			RANKX(
			    ALL( DimTecnico[NombreTecnico] ),
			    [EFICIENCIA_TECNICOS],
			    ,
			    DESC,
			    DENSE
			)
			
			```
		formatString: 0
		lineageTag: cbe73dce-7398-4cdc-89d4-747ffb338177

	measure ORDENES_ENPROCESO = CALCULATE(COUNTROWS(FactOrdenesTrabajo), FactOrdenesTrabajo[Estado] = "En Proceso")
		formatString: 0
		lineageTag: f714981a-a839-4c4c-8d25-343d39fc648e

	measure ORDENES_ENPROCESO_PORCENTAJE = [ORDENES_ENPROCESO]/[NUM_ORDERS]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: d99e701a-9421-457c-bb99-993b48f9e93b

	measure ORDENES_PENDIENTE = CALCULATE(COUNTROWS(FactOrdenesTrabajo), FactOrdenesTrabajo[Estado] = "Pendiente")
		formatString: 0
		lineageTag: c84954c9-8b0a-40da-ad11-f38025f3e931

	measure ORDENES_PENDIENTE_PORCENTAJE = [ORDENES_PENDIENTE]/[NUM_ORDERS]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: b66c45fb-12a2-474e-b308-221c3200591b

	measure BENEFICIO_ALINEACION = CALCULATE(SUM(FactOrdenesTrabajo[CostoTotal]), DimServicio[Categoria] = "Alineación")
		lineageTag: 058f6529-f383-4277-95f5-da716d416c04

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BENEFICIO_INSPECCION = CALCULATE(SUM(FactOrdenesTrabajo[CostoTotal]), DimServicio[Categoria] = "Inspección")
		lineageTag: ccd3d946-5d5b-4881-9a27-3f4ceef7eebc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BENEFICIO_REVISION = CALCULATE(SUM(FactOrdenesTrabajo[CostoTotal]), DimServicio[Categoria] = "Revisión")
		lineageTag: f321f0b2-9190-46e0-8138-fef25be360d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BENEFICIO_SUSPENSION = CALCULATE(SUM(FactOrdenesTrabajo[CostoTotal]), DimServicio[Categoria] = "Suspensión")
		lineageTag: 301cf6c7-d5e9-4d83-8425-5c28ee86d5b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MostrarPorTecnico = ```
			
			IF(
			    HASONEVALUE(DimTecnico[NombreTecnico]),
			    1,
			    0
			)
			
			```
		formatString: 0
		lineageTag: a5faa63e-1190-4e68-a94d-adb1cca34297

	measure RendimientoTecnico = ```
			
			CALCULATE(
			    COUNTROWS(FactOrdenesTrabajo),
			    FactOrdenesTrabajo[Estado] = "Terminado"
			)
			
			```
		formatString: 0
		lineageTag: aa9d5a3c-3cea-4fa1-8308-60c8877f958f

	measure OrdenesPorServicio = ```
			
			COUNTROWS(FactOrdenesTrabajo)
			
			```
		formatString: 0
		lineageTag: 77d86d3c-6c16-4e3c-8235-8bb697e57054

	measure OrdenesTerminadasPorTecnico = ```
			
			IF (
			    NOT ISFILTERED(DimTecnico[NombreTecnico]),
			    CALCULATE(
			        COUNTROWS(FactOrdenesTrabajo),
			        FactOrdenesTrabajo[Estado] = "Terminado"
			    )
			)
			
			```
		formatString: 0
		lineageTag: c02bf74c-c8ff-4cdd-8ffd-1c3926cece50

	measure Top8Tecnicos = ```
			
			VAR RankTecnico =
			    RANKX(
			        ALL(DimTecnico[NombreTecnico]),
			        CALCULATE(COUNT(FactOrdenesTrabajo[IdOrdenTrabajoDW])),
			        ,
			        DESC
			    )
			RETURN
			IF(
			    RankTecnico <= 8,
			    CALCULATE(
			        COUNT(FactOrdenesTrabajo[IdOrdenTrabajoDW])
			    )
			)
			
			```
		formatString: 0
		lineageTag: edcea721-97e6-4a3b-9561-5e4bd00eaa56

	measure GraficoTecnicosSmart = ```
			
			VAR ConteoSeleccion =
			    COUNTROWS(VALUES(DimTecnico[NombreTecnico]))
			RETURN
			SWITCH(
			    TRUE(),
			    ConteoSeleccion = 1, BLANK(),         -- Mostrar gráfico de servicios
			    ConteoSeleccion > 1, 
			        CALCULATE(COUNT(FactOrdenesTrabajo[IdOrdenTrabajoDW])),  -- Mostrar todos los técnicos
			    CALCULATE(
			        COUNT(FactOrdenesTrabajo[IdOrdenTrabajoDW])
			    )  -- Mostrar Top 8 cuando no hay selección
			)
			
			```
		formatString: 0
		lineageTag: e54b6354-623e-4d73-ad1a-52d7ecc75a27

	measure BrechaTiempo = ```
			
			SUM(factordenestrabajo[tiemporeal]) - SUM(factordenestrabajo[tiempoestimado])
			
			```
		formatString: 0
		lineageTag: 556528c8-86c8-4605-8c73-09538c2c44cb

	measure ConteoServicios = ```
			COUNT(factordenestrabajo[idordentrabajoDW])
			
			```
		formatString: 0
		lineageTag: ebbba910-d616-435e-b962-3e89cc643aa5

	measure Costo_Total = ```
			SUM(factordenestrabajo[costototal])
			
			```
		lineageTag: d8aa653f-cb7b-4941-a87c-795c4129f179

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CostoMaterial = ```
			
			SUMX(
			    FactRepuestosUsados,
			    FactRepuestosUsados[costounitario] * FactRepuestosUsados[cantidadutilizada]
			)
			
			```
		lineageTag: 67dc930f-b202-4e76-b88d-c4fa9cc85891

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Egresos_Estimados = ```
			SUM(factordenestrabajo[costototal]) * 0.65
			
			```
		lineageTag: 6e1e036b-fde0-46d4-9666-78b1f39d53d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GastoPromedioPorVehiculo =
			
			AVERAGEX(
			    VALUES(dimvehiculo[idvehiculodw]),
			    CALCULATE(SUM(factordenestrabajo[costototal]))
			)
		lineageTag: 7084d024-8007-4575-b271-d693415db466

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Ingresos_Mensuales = ```
			SUM(factordenestrabajo[costototal])
			
			```
		lineageTag: 2b813edd-cc78-474c-b02c-969f30232b53

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TiempoEstimadoTotal = SUM(factordenestrabajo[tiempoestimado])
		formatString: 0
		lineageTag: 0c101d64-291d-46e4-bbdf-e1d670ee3cd8

	measure TiempoRealTotal = ```
			SUM(factordenestrabajo[tiemporeal])
			
			```
		formatString: 0
		lineageTag: 71eb4d9f-28b7-431a-9b22-15ee3e609148

	measure TotalVehiculosAtendidos = ```
			
			DISTINCTCOUNT(factordenestrabajo[idvehiculodw])
			
			```
		formatString: 0
		lineageTag: d24dfb96-cab9-49dc-981a-885c35515fe7

	measure Costo_Servicio = AVERAGE(factordenestrabajo[costototal])
		lineageTag: 391714fd-ce58-47e0-bcd1-b76c01b9ef5b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition MEDIDAS = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

